name: Workflows
on: push
jobs:
  job_1:
    name: To Do List
    runs-on: ubuntu-latest
    steps:
      - name: Decrypt secret
        run: 
          if [ "$PASSWORD" -eq "manizales"]
          then 
            echo "$LIST"
          fi
        env: 
          PASSWORD: ${{ secrets.MENSAJE_OCULTO }}
          LIST: ${{ secrets.TO_DO_LIST }}