name: Workflows
on: push
jobs:
  job_1:
    name: To Do List
    runs-on: ubuntu-latest
    steps:
      - name: Decrypt secret
        run: 
          if [ "$PASSWORD" == "manizales"]
          then
            echo "yes"
          fi
        env: 
          PASSWORD: ${{ secrets.MENSAJE_OCULTO }}